### ISSUE TITLE
Timestamps at major steps in the analysis

### ISSUE THREAD

**Issue by torognes** [uio-bmi/compairr#23]
Log timestamps at major steps in the analysis. E.g. before and after reading files, etc.

**Comment by frederic-mahe** [comment]
I recommend to use the amazing [`std::chrono`](https://en.cppreference.com/w/cpp/header/chrono) library. For instance, in C++11:
```C++
#include <chrono>

auto t0 = std::chrono::steady_clock::now();
do_some_work();
auto t1 = std::chrono::steady_clock::now();
std::cout << {t1 - t0}.count() << "s\n"; // output seconds
```
