### ISSUE TITLE
Unable to upgrade version

### ISSUE THREAD

**Issue by svalkiers** [uio-bmi/compairr#33]
Hi, I downloaded the latest version of compairr (1.7.0) and compiled it according to the instructions in the readme. However, when I check the version after installation (using `compairr -v`) it shows version 1.6.1.

Also, uninstalling via:
```
make uninstall
```
or
```
sudo make uninstall
```
doesn't work, and returns:
```
make: *** No rule to make target 'install'.  Stop.
```

Any idea how to solve this issue?

**Comment by torognes** [comment]
Hi,

There is no `uninstall` rule for `make` for compairr, so you'll have to delete the binary manually (usually in `/usr/local/bin/compairr`). Reinstalling (with `make install`) should overwrite the old version.

Did you have compairr version 1.6.1 installed earlier? It may be the old version that runs when you issue `compairr -v`.

You could try to run `which compairr` to see where the current version is installed.

**Comment by svalkiers** [comment]
Thank you. The following procedure worked for me:

1. Locate and remove the binaries.
2. Reinstall the software.
3. Manually export the path to the executable.
