### ISSUE TITLE
Extracting information on the distance

### ISSUE THREAD

**Issue by vanessajmh** [uio-bmi/compairr#37]
Hello,
Is it possible to add a column in the output file with the calculated distance when performing a clustering analysis?
Thanks !

**Comment by torognes** [comment]
Hi

Thanks for the suggestion. It is definitely something we consider to implement, and it seems to be a useful feature. 

This issue is related to issue #36, where we suggest a feature to list the distances between all-vs-all sequences.

I cannot say how quickly we can do this, though.

**Comment by torognes** [comment]
I've added a function that may serve your purpose. It does not work with clustering, but with overlap compuations. But you can now compare a set of repertoires with itself and get the distances using the `--distance` option.

The new `--distance` option will write the distance between the sequences to the pairs file when computing overlaps. This is usually the Hamming distance (minimum number of substitutions needed), unless the `--indel` (or `-i´) option is specified (only allowed with d=1), in which case the distance is the Levenshtein distance (minimum number of substitutions or indels).

I hope this will help you.
