### ISSUE TITLE
New feature: Copy additional columns from input to output files

### ISSUE THREAD

**Issue by torognes** [uio-bmi/compairr#39]
Make a CompAIRR parameter called something like `columns-to-keep`, where the names of additional columns of interest that are not transferred by default could be specified. So if the user specifies `--columns-to-keep epitope`, the `pairs` file has additional columns `epitope_1` and `epitope_2`. And if the `epitope` column is only present in one of the input files, the fields in the `pairs` file could just be empty rather than throwing an error. This feature could be of general use for people who want to further analyse the sequences in the `pairs` file, it's essentially just transferring additional sequence metadata so the user does not have to map this data back to the input files.

**Comment by LonnekeScheffer** [comment]
minor comment: I have in the meantime realised that there are multiple columns I would need to keep as opposed to just a single one, though I suppose it was already planned to support keeping multiple columns

**Comment by torognes** [comment]
This and the other features you requested are now available in version 1.10.0 just released. Enjoy!
